name: Actualizar Agenda PirloTV
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Dependencias Directamente
        run: pip install requests

      - name: Ejecutar Scraper Bot
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
        run: python scraper_bot.py
